// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM3f1VR8sAs4En9mwshi0Ehzpvyb0jU3Q',
    appId: '1:928778812133:web:c2ceab3df843309072320c',
    messagingSenderId: '928778812133',
    projectId: 'fir-authflutter-c86b4',
    authDomain: 'fir-authflutter-c86b4.firebaseapp.com',
    storageBucket: 'fir-authflutter-c86b4.appspot.com',
    measurementId: 'G-4WGFQZ5FXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdsdZ8P3XrDgTDI0kkFRXowTQB0l-_dGg',
    appId: '1:928778812133:android:6256cc6db70ae43d72320c',
    messagingSenderId: '928778812133',
    projectId: 'fir-authflutter-c86b4',
    storageBucket: 'fir-authflutter-c86b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-nIOvKnMYo-HqN1Vq44zgQMaAE94WCfE',
    appId: '1:928778812133:ios:51ad38f4f00f18ac72320c',
    messagingSenderId: '928778812133',
    projectId: 'fir-authflutter-c86b4',
    storageBucket: 'fir-authflutter-c86b4.appspot.com',
    iosBundleId: 'com.example.googleAuthenticationProject',
  );
}
